name: Build and deploy to server

on:
  push:
    branches:
      - test # replace in production

jobs:
  docker:
    name: Create docker image and push to registry, then start image
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/${{ github.event.repository.name }}:latest
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Pull image and run container with .env variables from secrets
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_LOGIN }} -p ${{ secrets.REGISTRY_PASSWORD }} &&
            docker pull ${{ secrets.REGISTRY_URL }}/${{ github.event.repository.name }}:latest &&
            echo -e "${{ secrets.ENV }}" > env.list &&
            docker run --restart=always --env-file ./env.list --net=host -d -p ${{ secrets.RUN_PORT }}:${{ secrets.RUN_PORT }} --name=${{ github.event.repository.name }} ${{ secrets.REGISTRY_URL }}/${{ github.event.repository.name }}:latest &&
            docker image prune --filter="dangling=true" -f
