name: Deploy

on:
  push:
    branches:
      - test # replace to main before use

jobs:
  deploy:
    name: Deploy to server and start container using Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build new image
        run: docker build -t ${{ secrets.PROJECT_NAME }}:latest .
      - name: Export build to file
        run: docker save -o ${{ secrets.PROJECT_NAME }}.tar ${{ secrets.PROJECT_NAME }}:latest
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Move Docker image to server folder
        run: rsync -avz ${{ secrets.PROJECT_NAME }}.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/tmp
      - name: Import image and run container with .env variables from secrets
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker load < /tmp/${{ secrets.PROJECT_NAME }}.tar &&
            docker stop ${{ secrets.PROJECT_NAME }} || true &&
            docker rm ${{ secrets.PROJECT_NAME }} || true &&
            echo -e "${{ secrets.ENV }}" > env.list &&
            docker run --restart=always --env-file ./env.list --net=host -d -p ${{ secrets.RUN_PORT }}:${{ secrets.RUN_PORT }} --name=${{ secrets.PROJECT_NAME }} ${{ secrets.PROJECT_NAME }}:latest &&
            docker image prune --filter="dangling=true" -f &&
            rm env.list &&
            rm /tmp/${{ secrets.PROJECT_NAME }}.tar
